[package]
name = "soundtest"
version = "0.1.0"
authors = ["Sam Noedel <sam.noedel@gmail.com>"]
edition = "2018"

[dependencies]
alsa-sys = "^0.3.1"
dasp = { version = "^0.11.0", features = [ "signal" ] }
derive_builder = "^0.10.2"
nix = "^0.22.0"
